server:
  port: 8001

spring:
  application:
    name: cly-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    ##注册中心
  cloud:
    consul:
      host: 01.consul.server.ccx.net
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true
        healthCheckPath: /actuator/health
        health-check-critical-timeout: 60s
        healthCheckInterval: 30s
        prefer-ip-address: true
        health-check-timeout: 30s
        instance-id: cly-${spring.cloud.client.ip-address}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cly.springcloud.entities
